server:
  port: 8181

spring:
  sql:
      init:
        mode: always
  datasource:
#    url: jdbc:h2:file:~/jobs-search/erplab/db
    url: jdbc:h2:mem:erpdb
    username: sa
    password: 1234
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console.enabled: true
api:
  third-services:
    product-api:
      base-url: https://61abf188264ec200176d437c.mockapi.io
      time-out: 3000